authors:
  tshrjn:
    name: Tushar Jain
    description: Creator
    avatar: https://pbs.twimg.com/profile_images/1157999746486865920/Vw-OWciC_400x400.jpg
    url: https://twitter.com/intent/follow?screen_name=tusharjain_007
  jxnl:
    name: Jason Liu
    description: Creator
    avatar: https://pbs.twimg.com/profile_images/1724672723748638720/qOBwmkOI_400x400.jpg
    url: https://twitter.com/intent/follow?screen_name=jxnlco
  ivanleomk:
    name: Ivan Leo
    description: Contributor
    avatar: https://pbs.twimg.com/profile_images/1524186822389026816/sWRHRIkY_400x400.jpg
    url: https://twitter.com/intent/follow?screen_name=ivanleomk
